# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: BUILD WORKFLOW

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"
      - "master"
    types: [ opened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - run: cat src/main/resources/application.properties

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean test
