name: Dev Deployment

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    environment: DEV
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v3.4.1

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - run: cat src/main/resources/application.properties

      #  Package jar

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true


      # Heroku login
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP }}

        run: heroku container:login

      # Push the Docker image to Heroku Container Registry
      - name: Publish to Dev environment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP }}
          V_HOST: ${{ secrets.DB_HOST }}
          V_PORT: ${{ secrets.DB_PORT }}
          V_NAME: ${{ secrets.DB_NAME }}
          V_USER: ${{ secrets.DB_USER }}
          V_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: |
          heroku config:set -a ${{ secrets.HEROKU_APP }} DB_HOST=${{ secrets.DB_HOST }}
          heroku config:set -a ${{ secrets.HEROKU_APP }} DB_PORT=${{ secrets.DB_PORT }}
          heroku config:set -a ${{ secrets.HEROKU_APP }} DB_NAME=${{ secrets.DB_NAME }}
          heroku config:set -a ${{ secrets.HEROKU_APP }} DB_USER=${{ secrets.DB_USER }}
          heroku config:set -a ${{ secrets.HEROKU_APP }} DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          heroku container:login
          heroku container:push web -a ${{ secrets.HEROKU_APP }}
          heroku container:release web -a ${{ secrets.HEROKU_APP }}